### PR TITLE
Jinja2 support added.

### LINKED ISSUE #28: Extensions for Jinja2 template support
The README mentions how to use the library for the commands, but there is no mention of it regarding templates. There doesn't seem to be an extension in the source, is there perhaps a function we can pass to the Jinja2 environment?

### PR DESCRIPTION
**Pull request by AndreasBackx**
Resolves #28

### CODE REVIEW

**Comment by AndreasBackx** [comment]
@jrief Can this be merged?

**Comment by jrief** [comment]
Since I do not use Jinja2, at least not at the moment, I might be unable to maintain this feature.
Would you be willing to support Jinja2 for future releases of this app?

**Comment by AndreasBackx** [comment]
@jrief no problem. I'll watch the repo and you can mention me if you need my help on something.

**Comment by jrief** [comment]
OK. Please also add a line or two to the section named changes.

**Comment by AndreasBackx** [comment]
Add something to the changelog you mean? Under what version?

**Comment by jrief** [comment]
It's already named 0.3.4.dev0 and will become the next release.

**Comment by jrief** [comment]
Hi @AndreasBackx 
today I wanted to add support for sass/scss in Media classes (as used in the Django admin) and therefore I had to refactor the code.
What I was wondering, what is the ``source_file `` for? For me it seems as if  ``self._source_file`` is just initialized, but never used.

Can we work together on a separate branch in order to implement this, without loosing Jinja2 support?

**Comment by AndreasBackx** [comment]
`self._source_file` is initialised when using Jinja2, but the Django Template engine doesn't use it and falls back to `self.source[0].name` which was in the code and refers to the source template file (where the tag is used). See the `SassSrcNode.source_file` property.

The Jinja2 extension simply uses the node you implemented and acts like a wrapper around it, see [`SassSrc._sass_src_support`](https://github.com/jrief/django-sass-processor/blob/master/sass_processor/jinja2/ext.py#L30-L32). I would like to help, but am leaving on vacation at the end of the week and won't be back till the end of the month unfortunately. I am happy to work on it together when I get back. There shouldn't be any issues with the Jinja2 extension as long as `SassSrcNode.render` keeps doing what it is doing right now.

**Comment by jrief** [comment]
I've finished the refactoring now, available on this branch https://github.com/jrief/django-sass-processor/tree/media-processor

I've never worked with Jinja2, so please excuse my missing knowledge.

In Django templates you pass in the path of the scss file in the constructor of ``SassSrcNode``, while for me it seems as if in Jinja2 this path is passed in while rendering the templatetag.

I now refactored the code into a ``SassProcessor`` doing the heavy lifting and a much smaller ``SassSrcNode`` doing the template tag stuff. This allows me to reuse the ``SassProcessor`` outside of  templatetags, for instance in media classes and properties, as used by Django admin.

Please have a look at the branch. I believe it should be quite simple to re-add Jinja2 support again. If you can do it this week I'll release it with version 0.4.0, otherwise I will temporarily deactivate Jinja2 support and tell Jinja2 users to use version 0.3.4 until this is fixed. I unfortunately don't have the time to test this with Jinja2 for now.

Have a nice vacation!

**Pull request merged**
