### PR TITLE
make compatible with ManifestStaticFilesStorage

### PR DESCRIPTION
**Pull request by jrief**

### CODE REVIEW

**Review by mauritsvanrees — COMMENTED** [review]
Following the updated README from this PR fixed the incompatibility for me: setting `SASS_PROCESSOR_STORAGE` and `SASS_PROCESSOR_STORAGE_OPTIONS` to the given values. So that part of the PR is good, I would say.

The new code is not actually needed in my case it seems, but the changes make the working clearer, so it seems good. I don't really know this package though: another colleague introduced this as dependency in the project.

Quick background: 

- Old situation: Django 3.0 with django-sass-processor 0.8.2. My old settings worked fine.
- New situation: Django 3.2 with django-sass-processor 1.0.1. My old settings gave errors like `ValueError: Missing staticfiles manifest entry for 'images/favicon.png'`. With the updated settings, it is fine again.

**Comment by Natureshadow** [comment]
Huh. I have not yet understood what the special case with the manifest storage is. Maybe we just need a second storage class the uses the `ManifestStorageMixin`?

I will read up on this in the following days.

N.B. It would be great if you could separate whitespace and typo changes that are not related into separate commits to make handling of potential bisects, reverts and the like in the future easier.

**Comment by jrief** [comment]
Since @mauritsvanrees and myself experienced an improvement using these code changes, I'm going to merge this now and release version 1.1.

**Comment by jrief** [comment]
@Natureshadow Without this PR, CSS files delivered by Django are unhashed. This may result in delivering outdated CSS files, since browsers and proxies are not informed to use a newer version.
Since you experienced problems in combination with S3, I changed this feature. This [branch](https://github.com/jrief/django-sass-processor/tree/manifest-static-files-storage) may solve both problems.

@mauritsvanrees could you please test with the new branch and report your experience.

**Comment by Natureshadow** [comment]
> Without this PR, CSS files delivered by Django are unhashed

Can you please provide a minimal Django project to reproduce this issue?

**Comment by jrief** [comment]
here are my relevant configurations in `settings.py`:

```python
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

INSTALLED_APPS = [
    ...
    'sass_processor',
    ...
]

STATIC_ROOT = BASE_DIR / 'workdir/static'  # or whereever you keep temporarily compiled files
STATIC_URL = '/static/'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]

# if you want to access files in node_modules directly
STATICFILES_DIRS = [
    ('node_modules', BASE_DIR / 'node_modules'),
]
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
# after applying this path, this will change to:
# STATICFILES_STORAGE = 'sass_processor.storage.ManifestStaticFilesStorage' 

 # optional, if you `@import ...` in SCSS from special paths, otherwise leave empty
SASS_PROCESSOR_INCLUDE_DIRS = ['path/to/static']

SASS_PROCESSOR_FAIL_SILENTLY = not DEBUG
SASS_PROCESSOR_STORAGE = 'django.contrib.staticfiles.storage.FileSystemStorage'
SASS_PROCESSOR_STORAGE_OPTIONS = {
    'location': STATIC_ROOT,
    'base_url': STATIC_URL,
}
```

**Comment by Natureshadow** [comment]
> SASS_PROCESSOR_STORAGE = 'django.contrib.staticfiles.storage.FileSystemStorage'

That line forcefully disables the `ManifestStaticFilesStorage`. Leaving out this line makes `compilescss` use the configured `STATICFILES_STORAGE` and yields a `style.0123456789abcd.css` as expected.

**Comment by jrief** [comment]
In version 1.2.2 (and Django-4.0.6), if I use

```python
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
SASS_PROCESSOR_STORAGE = STATICFILES_STORAGE  # commenting this setting has the same effect

STATIC_ROOT = 'path/to/staticfiles'
```

and I delete the folder `path/to/staticfiles` and then run `./manage.py compilescss` with `DEBUG = False`, then 
Django complains in `django/django/contrib/staticfiles/storage.py:465` with a `ValueError` because it can't open the manifest JSON file.

btw., overriding the value `manifest_strict = False` doesn't help either.

**Comment by Natureshadow** [comment]
Did you also run collectstatic?

**Comment by jrief** [comment]
> Did you also run collectstatic?

after running `./manage.py compilescss`. Running it before doesn't make sense.

**Comment by Natureshadow** [comment]
> after running ./manage.py compilescss. Running it before doesn't make sense.

Obviously.

And that still copies the file without adding it to the manifest?

**Comment by jrief** [comment]
> And that still copies the file without adding it to the manifest?

No, `./manage.py compilescss` aborts with a `ValueError` as mentioned before.

**Pull request merged**
