### PR TITLE
Releases/1.0.x with unit tests

### PR DESCRIPTION
**Pull request by jrief**
Please help me to review **django-sass-processor** for the first stable release 1.0.

Unit tests have been added with a coverage of >90% for Django templates. Jinja2 templates are not covered yet, so @AndreasBackx could you please add them, since you are the expert on that topic.

### CODE REVIEW

**Comment by AndreasBackx** [comment]
I will definitely add them. I'm immensely busy this week because I've got a deadline for my bachelor's thesis and "we" are on a big version change with a ton of features that are gonna be moved to production the coming weeks. I'll try to squeeze it in somewhere!

**Comment by jrief** [comment]
Thanks for your help.

**Comment by jrief** [comment]
@AndreasBackx I've added you to the contributors with write access. Feel free to adopt the Jinja2 related parts, as if they would be yours.

**Comment by jrief** [comment]
any news on this?

**Pull request merged**
